# Generated by Django 5.2.4 on 2026-02-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galleryimage_schoolinfo_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='contact_number_2',
            field=models.CharField(blank=True, default='8544240801', max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='address',
            field=models.TextField(default='Near Nagwati Asthan Kali Mandir, Barhiya'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='contact_number',
            field=models.CharField(default='9973605904', max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='email',
            field=models.EmailField(default='shivshaktipublicschool123@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='principal_name',
            field=models.CharField(default='Pawan Kumar', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_name',
            field=models.CharField(default='Shiv Shakti Public School', max_length=200),
        ),
    ]
