# Generated by Django 6.0.3 on 2026-04-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolinfo_contact_number_2_alter_schoolinfo_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('school_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='core.schoolclass')),
            ],
        ),
    ]
