# Generated by Django 6.0.3 on 2026-04-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feestructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
